sonar.organization=jonasbisang
sonar.projectKey=jonasbisang_sopra-fs26-group36-server

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=./src